
APP:
  RELEASE: false
  ENV: "localhost"
  PORT: 8001
  HOST: "https://localhost:3000"
  API: "https://localhost:8001"
  SECRETKEY: "63af325da4b94165aa1e65cd6869b7e743b5b7fc9d35e0358b42b4a623e2b045"
  DEFAULT_PROFILE: "https://media.istockphoto.com/illustrations/blank-man-profile-head-icon-placeholder-illustration-id1298261537?k=20&m=1298261537&s=170667a&w=0&h=6HzVJ1UqaJD_F8yyYP0Mk_gH1AKzBUkz5jZGnnK4INY="

HTTP_SERVER:
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 10s
  IDLE_TIMEOUT: 120s

STORAGE:
  BUCKET_NAME: "ecommerce-users"
  REGION: ""
  BASE_URL: "https://localhost:9000"
  ACCESS: "minioadmin"
  SECRET: "minioadmin"

POSTGRE_SQL:
  HOST: "localhost"
  USERNAME: "root"
  PASSWORD: "P@sswrd"
  PORT: 5432
  DATABASE_NAME: "ecommerce-users"
  DRIVER_NAME: "postgres"
  ENABLE: true

REDIS:
  HOST: "localhost"
  PORT: 6379
  PASSWORD: "P@ssw0rd"

SWAGGER:
  TITLE: "template API Docs"
  DESCRIPTION: "template API is application to ecommerce users"
  VERSION: "1.0"
  HOST: "localhost:8001"
  BASE_URL: "/api/v1"
  ENABLE: true

FIREBASE:
  CREDENTIAL: "./json/credential.json"

JWT:
  EXPIRE_TIME: 24h0m0s
  SECRET: "39bcae4f93d4e3fcd034f146c6c54d1067221e6f83fe672170f96b86e0ef76d7"
  REFRESH_EXPIRATION_TIME: 168h0m0s

ORDER:
  URL: "https://localhost:8002/api/v1"
  PATH:
    ORDER: "/order"